server:
  port: 9091

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/payments?createDatabaseIfNotExist=true
    username: root
    password: asnpa 94
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

stripe:
  key: sk_test_51PhyXHJN8fGaKLJrYMlUb4aUMxAnOg03RNUf5WFC6LNWETKe8w5ahXT9EpEkVKUKxilYm6p0CXWEqmW4NxCaHy9S00CwwLkOVT

